version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
      - ./assets:/app/assets
    networks:
      - davinci-network

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - davinci-network
    depends_on:
      - backend

networks:
  davinci-network:
    driver: bridge
