apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: davinci-doc-ingress
  namespace: doc-generator
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
  - hosts:
    - docs.davincisolutions.ai
    secretName: davinci-doc-tls
  rules:
  - host: docs.davincisolutions.ai
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: davinci-frontend
            port:
              number: 80
